"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(pages)/Navbar";
import { ReduxProvider } from "@/app/ReduxProvider";
import { usePathname } from "next/navigation";
import Footer from "./(pages)/Footer";
import { useEffect, useState } from "react";
import axios from "axios";
import { Divide, LoaderCircle, LoaderPinwheel } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


{/* <LoaderCircle /> */}

 export default function RootLayout({ children }) {
  const pathName = usePathname()
  const Hide = pathName === "/signUp" || pathName === "/signIn"

  const [loding,setlogin] = useState(true)
  

const ProductUrl = "https://strapi-backend-1-7qd7.onrender.com/api/products"

const get = async () => {
  try {
   const res = await axios.get(ProductUrl)
 
  } catch (error) {
    console.error(error);
    
  }finally{
    setlogin(false)
  }
}

useEffect(()=> {get()},[])



    
 
  return (
    <html lang="en">
      <script src="//code.tidio.co/r6fkxxov9sd4b8xt7fdkmq8ifyfrdmk5.js" async></script>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}

      >
        {loding ? (
          <div className="h-screen w-full items-center flex justify-center">
            <LoaderCircle className="h-12 w-12 text-green-800  animate-spin" />
            {/* <LoaderPinwheel className="h-12 w-12 text-green-800  animate-spin" /> */}
            </div>
        ) : (
          <>
        <ReduxProvider>
      {!Hide&&<Navbar />}
        {children}
        {!Hide&&<Footer />}
        </ReduxProvider>
        </>
        )}
       
      </body>
    </html>
  );
}
